<?php
/**
 * FulfillmentByLogisticsPartnerApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Connect APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Mirakl\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\Mirakl\ApiException;
use OpenAPI\Client\Mirakl\Configuration;
use OpenAPI\Client\Mirakl\HeaderSelector;
use OpenAPI\Client\Mirakl\ObjectSerializer;

/**
 * FulfillmentByLogisticsPartnerApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FulfillmentByLogisticsPartnerApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'fUL01' => [
            'multipart/form-data',
        ],
        'fUL06' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation fUL01
     *
     * Synchronize inventory as a logistics partner
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  \SplFileObject|null $file JSON file containing the list of offers to synchronize. The offer sku has to exist on the marketplace. Use &lt;code&gt;multipart/form-data&lt;/code&gt; with name &lt;code&gt;file&lt;/code&gt;.&lt;br/&gt; JSON format:&lt;br/&gt;&lt;pre&gt;[{&lt;br/&gt; \\\&quot;offer_sku\\\&quot;: \\\&quot;Offer SKU on the marketplace\\\&quot;,&lt;br/&gt; \\\&quot;gtin\\\&quot;: \\\&quot;Product barcode\\\&quot;,&lt;br/&gt; \\\&quot;product_title\\\&quot;: \\\&quot;Product title\\\&quot;,&lt;br/&gt; \\\&quot;quantity\\\&quot;: \\\&quot;Product quantity for this offer\\\&quot;&lt;br/&gt;}]&lt;/pre&gt; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL01'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Mirakl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function fUL01($associative_array)
    {
        $this->fUL01WithHttpInfo($associative_array);
    }

    /**
     * Operation fUL01WithHttpInfo
     *
     * Synchronize inventory as a logistics partner
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  \SplFileObject|null $file JSON file containing the list of offers to synchronize. The offer sku has to exist on the marketplace. Use &lt;code&gt;multipart/form-data&lt;/code&gt; with name &lt;code&gt;file&lt;/code&gt;.&lt;br/&gt; JSON format:&lt;br/&gt;&lt;pre&gt;[{&lt;br/&gt; \\\&quot;offer_sku\\\&quot;: \\\&quot;Offer SKU on the marketplace\\\&quot;,&lt;br/&gt; \\\&quot;gtin\\\&quot;: \\\&quot;Product barcode\\\&quot;,&lt;br/&gt; \\\&quot;product_title\\\&quot;: \\\&quot;Product title\\\&quot;,&lt;br/&gt; \\\&quot;quantity\\\&quot;: \\\&quot;Product quantity for this offer\\\&quot;&lt;br/&gt;}]&lt;/pre&gt; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL01'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Mirakl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function fUL01WithHttpInfo($associative_array)
    {
        $request = $this->fUL01Request($associative_array);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation fUL01Async
     *
     * Synchronize inventory as a logistics partner
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  \SplFileObject|null $file JSON file containing the list of offers to synchronize. The offer sku has to exist on the marketplace. Use &lt;code&gt;multipart/form-data&lt;/code&gt; with name &lt;code&gt;file&lt;/code&gt;.&lt;br/&gt; JSON format:&lt;br/&gt;&lt;pre&gt;[{&lt;br/&gt; \\\&quot;offer_sku\\\&quot;: \\\&quot;Offer SKU on the marketplace\\\&quot;,&lt;br/&gt; \\\&quot;gtin\\\&quot;: \\\&quot;Product barcode\\\&quot;,&lt;br/&gt; \\\&quot;product_title\\\&quot;: \\\&quot;Product title\\\&quot;,&lt;br/&gt; \\\&quot;quantity\\\&quot;: \\\&quot;Product quantity for this offer\\\&quot;&lt;br/&gt;}]&lt;/pre&gt; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL01'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fUL01Async($associative_array)
    {
        return $this->fUL01AsyncWithHttpInfo($associative_array)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation fUL01AsyncWithHttpInfo
     *
     * Synchronize inventory as a logistics partner
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  \SplFileObject|null $file JSON file containing the list of offers to synchronize. The offer sku has to exist on the marketplace. Use &lt;code&gt;multipart/form-data&lt;/code&gt; with name &lt;code&gt;file&lt;/code&gt;.&lt;br/&gt; JSON format:&lt;br/&gt;&lt;pre&gt;[{&lt;br/&gt; \\\&quot;offer_sku\\\&quot;: \\\&quot;Offer SKU on the marketplace\\\&quot;,&lt;br/&gt; \\\&quot;gtin\\\&quot;: \\\&quot;Product barcode\\\&quot;,&lt;br/&gt; \\\&quot;product_title\\\&quot;: \\\&quot;Product title\\\&quot;,&lt;br/&gt; \\\&quot;quantity\\\&quot;: \\\&quot;Product quantity for this offer\\\&quot;&lt;br/&gt;}]&lt;/pre&gt; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL01'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fUL01AsyncWithHttpInfo($associative_array)
    {
        $returnType = '';
        $request = $this->fUL01Request($associative_array);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'fUL01'
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  \SplFileObject|null $file JSON file containing the list of offers to synchronize. The offer sku has to exist on the marketplace. Use &lt;code&gt;multipart/form-data&lt;/code&gt; with name &lt;code&gt;file&lt;/code&gt;.&lt;br/&gt; JSON format:&lt;br/&gt;&lt;pre&gt;[{&lt;br/&gt; \\\&quot;offer_sku\\\&quot;: \\\&quot;Offer SKU on the marketplace\\\&quot;,&lt;br/&gt; \\\&quot;gtin\\\&quot;: \\\&quot;Product barcode\\\&quot;,&lt;br/&gt; \\\&quot;product_title\\\&quot;: \\\&quot;Product title\\\&quot;,&lt;br/&gt; \\\&quot;quantity\\\&quot;: \\\&quot;Product quantity for this offer\\\&quot;&lt;br/&gt;}]&lt;/pre&gt; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL01'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function fUL01Request($associative_array)
    {
        // unbox the parameters from the associative array
        $file = array_key_exists('file', $associative_array) ? $associative_array['file'] : null;
        $contentType = $associative_array['contentType'] ?? self::contentTypes['fUL01'][0];
        


        $resourcePath = '/api/fulfillment/inventory';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation fUL06
     *
     * List shipping methods as a logistics partner
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL06'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Mirakl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Mirakl\Model\FUL06Response200
     */
    public function fUL06($associative_array)
    {
        list($response) = $this->fUL06WithHttpInfo($associative_array);
        return $response;
    }

    /**
     * Operation fUL06WithHttpInfo
     *
     * List shipping methods as a logistics partner
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL06'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Mirakl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Mirakl\Model\FUL06Response200, HTTP status code, HTTP response headers (array of strings)
     */
    public function fUL06WithHttpInfo($associative_array)
    {
        $request = $this->fUL06Request($associative_array);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Mirakl\Model\FUL06Response200' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Mirakl\Model\FUL06Response200' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Mirakl\Model\FUL06Response200', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Mirakl\Model\FUL06Response200';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Mirakl\Model\FUL06Response200',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation fUL06Async
     *
     * List shipping methods as a logistics partner
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL06'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fUL06Async($associative_array)
    {
        return $this->fUL06AsyncWithHttpInfo($associative_array)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation fUL06AsyncWithHttpInfo
     *
     * List shipping methods as a logistics partner
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL06'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fUL06AsyncWithHttpInfo($associative_array)
    {
        $returnType = '\OpenAPI\Client\Mirakl\Model\FUL06Response200';
        $request = $this->fUL06Request($associative_array);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'fUL06'
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['fUL06'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function fUL06Request($associative_array)
    {
        // unbox the parameters from the associative array
        $contentType = $associative_array['contentType'] ?? self::contentTypes['fUL06'][0];
        

        $resourcePath = '/api/fulfillment/shipping/types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
