<?php
/**
 * A01Response200DefaultBillingInformationCorporateInformationComplementaryInformation
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Mirakl\Model;

use \ArrayAccess;
use \OpenAPI\Client\Mirakl\ObjectSerializer;

/**
 * A01Response200DefaultBillingInformationCorporateInformationComplementaryInformation Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class A01Response200DefaultBillingInformationCorporateInformationComplementaryInformation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'A01_Response_200_DefaultBillingInformation_CorporateInformation_ComplementaryInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'businessActivityCode' => 'string',
        'companyRegistrationCity' => 'string',
        'companyRegistrationProvince' => 'string',
        'companyShareholders' => 'string',
        'isInLiquidation' => 'bool',
        'legalForm' => 'string',
        'shareCapital' => 'float',
        'shareCapitalCurrency' => 'string',
        'soleTrader' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'businessActivityCode' => null,
        'companyRegistrationCity' => null,
        'companyRegistrationProvince' => null,
        'companyShareholders' => null,
        'isInLiquidation' => null,
        'legalForm' => null,
        'shareCapital' => null,
        'shareCapitalCurrency' => null,
        'soleTrader' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'businessActivityCode' => false,
        'companyRegistrationCity' => false,
        'companyRegistrationProvince' => false,
        'companyShareholders' => false,
        'isInLiquidation' => false,
        'legalForm' => false,
        'shareCapital' => false,
        'shareCapitalCurrency' => false,
        'soleTrader' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'businessActivityCode' => 'business_activity_code',
        'companyRegistrationCity' => 'company_registration_city',
        'companyRegistrationProvince' => 'company_registration_province',
        'companyShareholders' => 'company_shareholders',
        'isInLiquidation' => 'is_in_liquidation',
        'legalForm' => 'legal_form',
        'shareCapital' => 'share_capital',
        'shareCapitalCurrency' => 'share_capital_currency',
        'soleTrader' => 'sole_trader'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'businessActivityCode' => 'setBusinessActivityCode',
        'companyRegistrationCity' => 'setCompanyRegistrationCity',
        'companyRegistrationProvince' => 'setCompanyRegistrationProvince',
        'companyShareholders' => 'setCompanyShareholders',
        'isInLiquidation' => 'setIsInLiquidation',
        'legalForm' => 'setLegalForm',
        'shareCapital' => 'setShareCapital',
        'shareCapitalCurrency' => 'setShareCapitalCurrency',
        'soleTrader' => 'setSoleTrader'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'businessActivityCode' => 'getBusinessActivityCode',
        'companyRegistrationCity' => 'getCompanyRegistrationCity',
        'companyRegistrationProvince' => 'getCompanyRegistrationProvince',
        'companyShareholders' => 'getCompanyShareholders',
        'isInLiquidation' => 'getIsInLiquidation',
        'legalForm' => 'getLegalForm',
        'shareCapital' => 'getShareCapital',
        'shareCapitalCurrency' => 'getShareCapitalCurrency',
        'soleTrader' => 'getSoleTrader'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('businessActivityCode', $data ?? [], null);
        $this->setIfExists('companyRegistrationCity', $data ?? [], null);
        $this->setIfExists('companyRegistrationProvince', $data ?? [], null);
        $this->setIfExists('companyShareholders', $data ?? [], null);
        $this->setIfExists('isInLiquidation', $data ?? [], null);
        $this->setIfExists('legalForm', $data ?? [], null);
        $this->setIfExists('shareCapital', $data ?? [], null);
        $this->setIfExists('shareCapitalCurrency', $data ?? [], null);
        $this->setIfExists('soleTrader', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets businessActivityCode
     *
     * @return string|null
     */
    public function getBusinessActivityCode()
    {
        return $this->container['businessActivityCode'];
    }

    /**
     * Sets businessActivityCode
     *
     * @param string|null $businessActivityCode The business activity code of the company, known as <code>APE code</code> in France. <br/><i>Applies only when the operator is registered in the <code>EU</code>, and the seller is registered in <code>France</code>.</i>
     *
     * @return self
     */
    public function setBusinessActivityCode($businessActivityCode)
    {
        if (is_null($businessActivityCode)) {
            throw new \InvalidArgumentException('non-nullable businessActivityCode cannot be null');
        }
        $this->container['businessActivityCode'] = $businessActivityCode;

        return $this;
    }

    /**
     * Gets companyRegistrationCity
     *
     * @return string|null
     */
    public function getCompanyRegistrationCity()
    {
        return $this->container['companyRegistrationCity'];
    }

    /**
     * Sets companyRegistrationCity
     *
     * @param string|null $companyRegistrationCity The city of the company's registry office. <br/><i>Applies only when the operator is registered in the <code>EU</code> and the seller is registered in <code>France</code> or <code>Luxembourg</code>.</i>
     *
     * @return self
     */
    public function setCompanyRegistrationCity($companyRegistrationCity)
    {
        if (is_null($companyRegistrationCity)) {
            throw new \InvalidArgumentException('non-nullable companyRegistrationCity cannot be null');
        }
        $this->container['companyRegistrationCity'] = $companyRegistrationCity;

        return $this;
    }

    /**
     * Gets companyRegistrationProvince
     *
     * @return string|null
     */
    public function getCompanyRegistrationProvince()
    {
        return $this->container['companyRegistrationProvince'];
    }

    /**
     * Sets companyRegistrationProvince
     *
     * @param string|null $companyRegistrationProvince The initials of the company’s registry office province. Known as <code>Ufficio</code> in Italy. <br/><i>Applies only when the operator is registered in the <code>EU</code> and the seller is registered in <code>Italy</code>.</i>
     *
     * @return self
     */
    public function setCompanyRegistrationProvince($companyRegistrationProvince)
    {
        if (is_null($companyRegistrationProvince)) {
            throw new \InvalidArgumentException('non-nullable companyRegistrationProvince cannot be null');
        }
        $this->container['companyRegistrationProvince'] = $companyRegistrationProvince;

        return $this;
    }

    /**
     * Gets companyShareholders
     *
     * @return string|null
     */
    public function getCompanyShareholders()
    {
        return $this->container['companyShareholders'];
    }

    /**
     * Sets companyShareholders
     *
     * @param string|null $companyShareholders Indicates if there is a single shareholder or several shareholders. Known as <code>Socio Unico</code> in Italy. <br/><i>Applies only when the operator is registered in the <code>EU</code> and the seller is registered in <code>Italy</code>.</i>
     *
     * @return self
     */
    public function setCompanyShareholders($companyShareholders)
    {
        if (is_null($companyShareholders)) {
            throw new \InvalidArgumentException('non-nullable companyShareholders cannot be null');
        }
        $this->container['companyShareholders'] = $companyShareholders;

        return $this;
    }

    /**
     * Gets isInLiquidation
     *
     * @return bool|null
     */
    public function getIsInLiquidation()
    {
        return $this->container['isInLiquidation'];
    }

    /**
     * Sets isInLiquidation
     *
     * @param bool|null $isInLiquidation Indicates whether the company is in liquidation or not. <br/><i>Applies only when the operator is registered in the <code>EU</code></i>
     *
     * @return self
     */
    public function setIsInLiquidation($isInLiquidation)
    {
        if (is_null($isInLiquidation)) {
            throw new \InvalidArgumentException('non-nullable isInLiquidation cannot be null');
        }
        $this->container['isInLiquidation'] = $isInLiquidation;

        return $this;
    }

    /**
     * Gets legalForm
     *
     * @return string|null
     */
    public function getLegalForm()
    {
        return $this->container['legalForm'];
    }

    /**
     * Sets legalForm
     *
     * @param string|null $legalForm The legal form of the company. <br/><i>Applies only when the operator is registered in the <code>EU</code></i>
     *
     * @return self
     */
    public function setLegalForm($legalForm)
    {
        if (is_null($legalForm)) {
            throw new \InvalidArgumentException('non-nullable legalForm cannot be null');
        }
        $this->container['legalForm'] = $legalForm;

        return $this;
    }

    /**
     * Gets shareCapital
     *
     * @return float|null
     */
    public function getShareCapital()
    {
        return $this->container['shareCapital'];
    }

    /**
     * Sets shareCapital
     *
     * @param float|null $shareCapital The share capital of the company. <br/><i>Applies only when the operator is registered in the <code>EU</code></i>
     *
     * @return self
     */
    public function setShareCapital($shareCapital)
    {
        if (is_null($shareCapital)) {
            throw new \InvalidArgumentException('non-nullable shareCapital cannot be null');
        }
        $this->container['shareCapital'] = $shareCapital;

        return $this;
    }

    /**
     * Gets shareCapitalCurrency
     *
     * @return string|null
     */
    public function getShareCapitalCurrency()
    {
        return $this->container['shareCapitalCurrency'];
    }

    /**
     * Sets shareCapitalCurrency
     *
     * @param string|null $shareCapitalCurrency The share capital currency of the company. <br/><i>Applies only when the operator is registered in the <code>EU</code></i>
     *
     * @return self
     */
    public function setShareCapitalCurrency($shareCapitalCurrency)
    {
        if (is_null($shareCapitalCurrency)) {
            throw new \InvalidArgumentException('non-nullable shareCapitalCurrency cannot be null');
        }
        $this->container['shareCapitalCurrency'] = $shareCapitalCurrency;

        return $this;
    }

    /**
     * Gets soleTrader
     *
     * @return bool|null
     */
    public function getSoleTrader()
    {
        return $this->container['soleTrader'];
    }

    /**
     * Sets soleTrader
     *
     * @param bool|null $soleTrader Defines if the shop is a sole trader. When this option is set to true, additional information is asked to the shop. <i>Applies only when the operator is registered in the <code>EU</code></i>
     *
     * @return self
     */
    public function setSoleTrader($soleTrader)
    {
        if (is_null($soleTrader)) {
            throw new \InvalidArgumentException('non-nullable soleTrader cannot be null');
        }
        $this->container['soleTrader'] = $soleTrader;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


