<?php
/**
 * OrderUnitEmbeddable
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.18.3
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Mirakl\Model;
use \OpenAPI\Client\Mirakl\ObjectSerializer;

/**
 * OrderUnitEmbeddable Class Doc Comment
 *
 * @category Class
 * @description Additional data to be returned for order unit
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderUnitEmbeddable
{
    /**
     * Possible values of this enum
     */
    public const DELIVERY_ATTEMPT_TIMESTAMP_ISO = 'delivery_attempt_timestamp_iso';

    public const RETURN_UNIT = 'return_unit';

    public const TICKETS = 'tickets';

    public const DELIVERY = 'delivery';

    public const KSS_DELIVERY = 'kss_delivery';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DELIVERY_ATTEMPT_TIMESTAMP_ISO,
            self::RETURN_UNIT,
            self::TICKETS,
            self::DELIVERY,
            self::KSS_DELIVERY
        ];
    }
}


