<?php
/**
 * TicketTopic
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.18.3
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Mirakl\Model;
use \OpenAPI\Client\Mirakl\ObjectSerializer;

/**
 * TicketTopic Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TicketTopic
{
    /**
     * Possible values of this enum
     */
    public const ORDER_CANCEL = 'order_cancel';

    public const ORDER_PRODUCT_DEFECT = 'order_product_defect';

    public const ORDER_OTHER_QUESTION = 'order_other_question';

    public const DELIVERY_NOT_RECEIVED = 'delivery_not_received';

    public const DELIVERY_DELAYED = 'delivery_delayed';

    public const DELIVERY_WRONG_PRODUCTS = 'delivery_wrong_products';

    public const DELIVERY_PARTS_MISSING = 'delivery_parts_missing';

    public const DELIVERY_CHANGE_ADDRESS = 'delivery_change_address';

    public const DELIVERY_TO_STORE = 'delivery_to_store';

    public const DELIVERY_OTHER_QUESTION = 'delivery_other_question';

    public const RETURN_CHECK_STATUS = 'return_check_status';

    public const RETURN_REQUEST_LABEL = 'return_request_label';

    public const ISSUE_PAYPAL = 'issue_paypal';

    public const ISSUE_KLARNA = 'issue_klarna';

    public const ISSUE_CREDITCARD = 'issue_creditcard';

    public const ISSUE_SOFORT = 'issue_sofort';

    public const ISSUE_CONSORSFINANZ = 'issue_consorsfinanz';

    public const ISSUE_CASHINADVANCE = 'issue_cashinadvance';

    public const ISSUE_PAYBACK = 'issue_payback';

    public const ISSUE_BARZAHLEN = 'issue_barzahlen';

    public const ISSUE_COUPON = 'issue_coupon';

    public const INVOICE_NEEDED = 'invoice_needed';

    public const ADMONITION = 'admonition';

    public const ACCOUNT_NEWSLETTER = 'account_newsletter';

    public const ACCOUNT_LOGIN = 'account_login';

    public const ACCOUNT_CANCEL = 'account_cancel';

    public const ACCOUNT_OTHER = 'account_other';

    public const ACCOUNT_AGE_VERIFICATION = 'account_age_verification';

    public const PRODUCT_PROPERTIES = 'product_properties';

    public const PRODUCT_AVAILABILITY = 'product_availability';

    public const PRODUCT_OTHER_QUESTION = 'product_other_question';

    public const ACCOUNT_CASH_OUT_BALANCE = 'account_cash_out_balance';

    public const OLD_DEVICE_TAKE_BACK = 'old_device_take_back';

    public const OTHER_QUESTION = 'other_question';

    public const FRAUD = 'fraud';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ORDER_CANCEL,
            self::ORDER_PRODUCT_DEFECT,
            self::ORDER_OTHER_QUESTION,
            self::DELIVERY_NOT_RECEIVED,
            self::DELIVERY_DELAYED,
            self::DELIVERY_WRONG_PRODUCTS,
            self::DELIVERY_PARTS_MISSING,
            self::DELIVERY_CHANGE_ADDRESS,
            self::DELIVERY_TO_STORE,
            self::DELIVERY_OTHER_QUESTION,
            self::RETURN_CHECK_STATUS,
            self::RETURN_REQUEST_LABEL,
            self::ISSUE_PAYPAL,
            self::ISSUE_KLARNA,
            self::ISSUE_CREDITCARD,
            self::ISSUE_SOFORT,
            self::ISSUE_CONSORSFINANZ,
            self::ISSUE_CASHINADVANCE,
            self::ISSUE_PAYBACK,
            self::ISSUE_BARZAHLEN,
            self::ISSUE_COUPON,
            self::INVOICE_NEEDED,
            self::ADMONITION,
            self::ACCOUNT_NEWSLETTER,
            self::ACCOUNT_LOGIN,
            self::ACCOUNT_CANCEL,
            self::ACCOUNT_OTHER,
            self::ACCOUNT_AGE_VERIFICATION,
            self::PRODUCT_PROPERTIES,
            self::PRODUCT_AVAILABILITY,
            self::PRODUCT_OTHER_QUESTION,
            self::ACCOUNT_CASH_OUT_BALANCE,
            self::OLD_DEVICE_TAKE_BACK,
            self::OTHER_QUESTION,
            self::FRAUD
        ];
    }
}


