<?php
/**
 * TicketReason
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.18.3
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Mirakl\Model;
use \OpenAPI\Client\Mirakl\ObjectSerializer;

/**
 * TicketReason Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TicketReason
{
    /**
     * Possible values of this enum
     */
    public const PRODUCT_NOT_AS_DESCRIBED = 'product_not_as_described';

    public const PRODUCT_DEFECT = 'product_defect';

    public const PRODUCT_NOT_DELIVERED = 'product_not_delivered';

    public const PRODUCT_RETURN = 'product_return';

    public const CONTACT_OTHER = 'contact_other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRODUCT_NOT_AS_DESCRIBED,
            self::PRODUCT_DEFECT,
            self::PRODUCT_NOT_DELIVERED,
            self::PRODUCT_RETURN,
            self::CONTACT_OTHER
        ];
    }
}


