<?php
/**
 * IV01Response200InvoicesAutoInvoicePaymentInfoNzbsbTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Mirakl\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * IV01Response200InvoicesAutoInvoicePaymentInfoNzbsbTest Class Doc Comment
 *
 * @category    Class
 * @description IV01Response200InvoicesAutoInvoicePaymentInfoNzbsb
 * @package     OpenAPI\Client\Mirakl
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IV01Response200InvoicesAutoInvoicePaymentInfoNzbsbTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IV01Response200InvoicesAutoInvoicePaymentInfoNzbsb"
     */
    public function testIV01Response200InvoicesAutoInvoicePaymentInfoNzbsb()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nzban"
     */
    public function testPropertyNzban()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nzbsb"
     */
    public function testPropertyNzbsb()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
