<?php
/**
 * ST31RequestShipmentsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Mirakl\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ST31RequestShipmentsTest Class Doc Comment
 *
 * @category    Class
 * @description List of shipments additional information
 * @package     OpenAPI\Client\Mirakl
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ST31RequestShipmentsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ST31RequestShipments"
     */
    public function testST31RequestShipments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipmentAdditionalInformation"
     */
    public function testPropertyShipmentAdditionalInformation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
