<?php
/**
 * MultipleShipmentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Mirakl\Test\Api;

use \OpenAPI\Client\Mirakl\Configuration;
use \OpenAPI\Client\Mirakl\ApiException;
use \OpenAPI\Client\Mirakl\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MultipleShipmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MultipleShipmentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for sT01
     *
     * Create shipments.
     *
     */
    public function testST01()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sT06
     *
     * Delete shipments.
     *
     */
    public function testST06()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sT07
     *
     * Update shipment shipping origin.
     *
     */
    public function testST07()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sT11
     *
     * List shipments.
     *
     */
    public function testST11()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sT12
     *
     * List items to ship.
     *
     */
    public function testST12()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sT23
     *
     * Update carrier tracking information for shipments.
     *
     */
    public function testST23()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sT24
     *
     * Validate shipments as shipped.
     *
     */
    public function testST24()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sT26
     *
     * Validate shipments as ready to pick up.
     *
     */
    public function testST26()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sT31
     *
     * Update shipment additional information.
     *
     */
    public function testST31()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
