<?php
/**
 * ReportsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.18.3
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Mirakl\Test\Api;

use \OpenAPI\Client\Mirakl\Configuration;
use \OpenAPI\Client\Mirakl\ApiException;
use \OpenAPI\Client\Mirakl\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getReport
     *
     * Get meta-data for a single report by ID.
     *
     */
    public function testGetReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReports
     *
     * Get a list of your reports.
     *
     */
    public function testGetReports()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestAccountListingReport
     *
     * Queue an inventory report.
     *
     */
    public function testRequestAccountListingReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestAccountListingWithShopPriceReport
     *
     * Queue an inventory report.
     *
     */
    public function testRequestAccountListingWithShopPriceReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestCancellationsReport
     *
     * Queue a cancellations report..
     *
     */
    public function testRequestCancellationsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestCompetitorsComparerReport
     *
     * Queue a competitors comparison report.
     *
     */
    public function testRequestCompetitorsComparerReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestEansNotFoundReport
     *
     * Queue an EANs not found report.
     *
     */
    public function testRequestEansNotFoundReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestNewBookingsReport
     *
     * Queue a bookings report.
     *
     */
    public function testRequestNewBookingsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestNewSalesReport
     *
     * Queue a sales report.
     *
     */
    public function testRequestNewSalesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestProductDataChangesReport
     *
     * Queue a product data changes report.
     *
     */
    public function testRequestProductDataChangesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestProductDataImportFileErrorsReport
     *
     * Queue a product data import file errors report.
     *
     */
    public function testRequestProductDataImportFileErrorsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
