<?php
/**
 * ReturnsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Mirakl\Test\Api;

use \OpenAPI\Client\Mirakl\Configuration;
use \OpenAPI\Client\Mirakl\ApiException;
use \OpenAPI\Client\Mirakl\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReturnsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReturnsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for rT04
     *
     * Patch update returns.
     *
     */
    public function testRT04()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rT11
     *
     * List returns.
     *
     */
    public function testRT11()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rT21
     *
     * Accept or refuse a return request.
     *
     */
    public function testRT21()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rT25
     *
     * Validate returns as received.
     *
     */
    public function testRT25()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rT26
     *
     * Mark a return as compliant or non compliant.
     *
     */
    public function testRT26()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
